### PR TITLE
Cleaning up reference data

### PR DESCRIPTION
**Pull request by EduardJS**
Described in #120

### CODE REVIEW

**Comment by EduardJS** [comment]
I signed it!

**Comment by jwngr** [comment]
Thanks for opening this issue and sending off a PR for it! I think it's a good change and I'm sorry it cost you some lost time. In addition to deleting `this.data[bindVar]`, I think we also need to call `setState()` to set the bind variable's state to `undefined`:

```
var newData = {};
newData[bindVar] = undefined;
this.setState(newData);
```

Once you make that change, I'll go ahead and merge this in.

**Comment by EduardJS** [comment]
Hi @jwngr 

If I understood correctly, then I must say we already trigger `setState` on `bindVar` to `undefined` as seen here: https://github.com/firebase/reactfire/blob/master/src/reactfire.js#L392

Please let me know if that's not what you're talking about!

Cheers, and thanks for the reply!

**Comment by jwngr** [comment]
Wow 😨 Not sure how I missed that... I literally wrote the same exact code as we already have in the library. Mondays...

Anyway, this looks good! Merging it in.

**Comment by EduardJS** [comment]
Haha! I feel you regarding Mondays, though you missed the callback in your code  👍 

Have a good one and thanks for the merge!

**Pull request merged**
