### PR TITLE
Upgrade dependencies to react 15

### PR DESCRIPTION
**Pull request by ThariqS**
Tests and examples seem to work on my end.

### CODE REVIEW

**Comment by ThariqS** [comment]
I signed it!

**Comment by jwngr** [comment]
Thanks for sending this along. You also need to update the `bower.json` dependency. Also, can you update the React version for all the examples in the `/examples` directory?

**Comment by ThariqS** [comment]
Just did added the bower.json and examples!

**Comment by victoriafrench** [comment]
any updates on when this will be pushed? thanks

**Comment by jwngr** [comment]
Looks good! Thanks for the contribution! I'll get a new version of ReactFire (0.7.0) out within the hour.

**Comment by jwngr** [comment]
[ReactFire 0.7.0](https://github.com/firebase/reactfire/releases/tag/v0.7.0) is out! Thanks again!

**Pull request merged**
