### PR TITLE
direct url to visit the example demo when the user downloaded the entire…

### PR DESCRIPTION
**Pull request by ramyathulasingam**
When user downloads an entire repo navigating to the localhost displays the file structure. 

Updated the readme with a direct url to the commentbox example demo.

### CODE REVIEW

**Comment by jwngr** [comment]
Thanks a lot for the PR! Would you mind making the same change for [the other example](https://github.com/firebase/reactfire/blob/master/examples/todoApp/README.md)?

Also, we will need you to sign the Google CLA in order for this change to get merged in.

**Comment by ramyathulasingam** [comment]
@jwngr I have signed the CLA. Please verify.

**Comment by jwngr** [comment]
When I suggested adding the link for the todoApp example, I meant doing it in its own `README`, not the commentsBox `README`. Would you mind fixing that up?

**Comment by jwngr** [comment]
Thanks for the contribution!

**Pull request merged**
